#!/usr/bin/env bash
#configures an ubuntu server with these details:
#   - localhost resolves to 127.0.0.2
#   - faceebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 	localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts